# permissions for end users to edit tablefields.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tablefield-editor-role
rules:
- apiGroups:
  - apps.medulla.io
  resources:
  - tablefields
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.medulla.io
  resources:
  - tablefields/status
  verbs:
  - get
