# permissions for end users to view tables.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: table-viewer-role
rules:
- apiGroups:
  - apps.medulla.io
  resources:
  - tables
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.medulla.io
  resources:
  - tables/status
  verbs:
  - get
